### ISSUE TITLE
Produced .exe from glfw/window is flagged as a trojan by Nod32 

### ISSUE THREAD

**Issue by alexgrpds** [odin-lang/examples#39]
Running the glfw\window example ("odin.exe run glfw\window") triggers the Nod32 AV software that flags the produced executable as "a variant of Win64/TrojanDropper.Agent_AGen.N trojan". A false alarm to be sure, I'm posting this just in case someone wants to investigate further. 

![Screenshot 2024-03-29 151013](https://github.com/odin-lang/examples/assets/69468239/54e87ab0-7c47-4b47-a3df-b9b8d635493c)

**Comment by JesseRMeyer** [comment]
We've been seeing this.  It's a false positive, we presume, from Microsoft's machine learning threat detection, and it's wrong.

Please submit the application for clearance here: https://www.microsoft.com/en-us/wdsi/filesubmission and hopefully their model will learn not to blindly flag Odin executables as threatening..

**Comment by Kelimion** [comment]
> We've been seeing this. It's a false positive, we presume, from Microsoft's machine learning threat detection, and it's wrong.

In this case it's Eset's NOD32, a usually great antivirus - I've run it for years - but they too have machine learning heuristics that can be a bit daft.

Your best course of action would be to either whitelist `odin.exe` in the hope that the AV doesn't flag executables it creates, or build Odin from source if you haven't already. False positives seem to occur more often for people who use a release build instead of building the compiler themselves.
